get:
  tags:
  - Admin
  summary: Get custom course configs
  description: |
    Get all custom course configs
  security:
    - bearerAuth: []
  responses:
    200:
      description: Successful operation
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: "../../../schemas/custom/CourseConfig.yaml"
    400:
      description: Bad request
    401:
      description: Unauthorized
    500:
      description: Internal error
  x-core-function: GetCustomCourseConfigs
  x-data-type: model.CourseConfig
  x-authentication-type: Permissions
post:
  tags:
  - Admin
  summary: Create custom course config
  description: |
    Create a custom course config
  security:
    - bearerAuth: []
  requestBody:
    description: course config
    content:
      application/json:
        schema:
         $ref: "../../../schemas/custom/CourseConfig.yaml"
    required: true
  responses:
    200:
      description: Success
      content:
        text/plain:
          schema:
            type: string
            example: Success
    400:
      description: Bad request
    401:
      description: Unauthorized
    500:
      description: Internal error
  x-core-function: CreateCustomCourseConfig
  x-data-type: model.CourseConfig
  x-authentication-type: Permissions