openapi: 3.0.3
info:
  title: Rokwire LMS Building Block API
  description: LMS Building Block API Documentation
  version: 1.23.0
servers:
  - url: 'http://localhost/lms'
    description: Local server
  - url: 'https://api-dev.rokwire.illinois.edu/lms/doc'
    description: Development server
paths:
  /api/v1:
    get:
      '200':
        description: Successful operation
        content:
          text/plain:
            schema:
              type: string
      '400':
        description: Bad request
      '401':
        description: Unauthorized
      '500':
        description: Internal error
      tags:
        - api
      description: Wraps all Canvas V1 api requests
      operationId: V1Wrapper
      produces:
        - text/plain
      responses: null
  /api/courses:
    get:
      tags:
        - api
      summary: Get courses
      description: |
        Get courses
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/paths/~1api~1courses~1%7Bid%7D/get/responses/200/content/application~1json/schema'
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '500':
          description: Internal error
  '/api/courses/{id}':
    get:
      tags:
        - api
      summary: Get course by ID
      description: |
        Gets course by ID
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          description: ID of the course
          required: true
          style: simple
          explode: false
          schema: null
          type: string
        - name: include
          in: query
          description: 'include = enrollments,scores'
          schema: null
          type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    readOnly: true
                  name:
                    type: string
                  access_restricted_by_date:
                    type: boolean
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '404':
          description: Not Found
        '500':
          description: Internal error
  '/api/courses/{id}/assignment-groups':
    get:
      tags:
        - api
      summary: Get assignment-groups by ID
      description: |
        Gets assignment-groups by ID
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          description: ID of the course
          required: true
          style: simple
          explode: false
          schema: null
          type: string
        - name: include
          in: query
          description: 'include = enrollments,scores'
          schema: null
          type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  assigments:
                    type: object
                    properties:
                      id:
                        readOnly: true
                        type: string
                      name:
                        type: string
                      course_id:
                        type: integer
                      html_url:
                        type: string
                      position:
                        type: integer
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '404':
          description: Not Found
        '500':
          description: Internal error
  '/api/courses/{id}/users':
    get:
      tags:
        - api
      summary: Get user by ID
      description: |
        Gets user by ID
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          description: ID of the course
          required: true
          style: simple
          explode: false
          schema: null
          type: string
        - name: include
          in: query
          description: 'include = enrollments,scores'
          schema: null
          type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  enrollments:
                    type: object
                    properties:
                      id:
                        type: integer
                      type:
                        type: string
                      grade:
                        type: object
                        properties:
                          current_score:
                            type: float64
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '404':
          description: Not Found
        '500':
          description: Internal error
  /api/user/self:
    get:
      tags:
        - api
      summary: Get current user
      description: |
        Get current user
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/paths/~1api~1courses~1%7Bid%7D~1users/get/responses/200/content/application~1json/schema'
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '500':
          description: Internal error
  /admin/nudges:
    get:
      tags:
        - Admin
      summary: Get nudges
      description: |
        Get nudges
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      readOnly: true
                      type: string
                    name:
                      type: string
                    body:
                      type: string
                    params:
                      type: object
                      nullable: true
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '500':
          description: Internal error
    post:
      tags:
        - Admin
      summary: Create Nudge
      description: |
        Creates Nudge
      security:
        - bearerAuth: []
      requestBody:
        description: creates one nudge
        content:
          application/json:
            schema:
              required:
                - name
                - body
                - params
              type: object
              properties:
                name:
                  type: string
                body:
                  type: string
                params:
                  type: object
                  nullable: true
        required: true
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                type: string
                example: Success
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '500':
          description: Internal error
  '/admin/nudges/{id}':
    put:
      tags:
        - Admin
      summary: Update nudge by ID
      description: |
        Updates nudge by ID
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          description: ID of the nudge that needs to be updated
          required: true
          style: simple
          explode: false
          schema:
            type: string
      requestBody:
        description: update one nudge
        content:
          application/json:
            schema:
              required:
                - id
                - name
                - body
                - params
              type: object
              properties:
                id:
                  readOnly: true
                  type: string
                name:
                  type: string
                body:
                  type: string
                params:
                  type: object
                  nullable: true
        required: true
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                type: string
                example: Success
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '500':
          description: Internal error
    delete:
      tags:
        - Admin
      summary: Delete nudge
      description: |
        Delete nudge
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          description: The nudge ID
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '500':
          description: Internal error
