openapi: 3.0.3
info:
  title: Rokwire LMS Building Block API
  description: LMS Building Block API Documentation
  version: 1.23.0
servers:
  - url: 'http://localhost/lms'
    description: Local server
  - lms: 'https://api-dev.rokwire.illinois.edu/lms'
    description: Development server
paths:
  /api/v1:
    get:
      '200':
        description: Successful operation
        content:
          text/plain:
            schema:
              type: string
      '400':
        description: Bad request
      '401':
        description: Unauthorized
      '500':
        description: Internal error
      tags:
        - api
      description: Wraps all Canvas V1 api requests
      operationId: V1Wrapper
      produces:
        - text/plain
      responses: null
  /api/courses:
    get:
      tags:
        - api
      summary: Get courses
      description: |
        Get courses
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/paths/~1api~1courses~1%7Bid%7D/get/responses/200/content/application~1json/schema'
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '500':
          description: Internal error
  '/api/courses/{id}':
    get:
      tags:
        - api
      summary: Get course by ID
      description: |
        Gets course by ID
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: query
          description: ID of the course
          required: true
          style: form
          explode: false
          schema: null
          type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    readOnly: true
                  name:
                    type: string
                  accessRestrictedByDate:
                    type: boolean
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '404':
          description: Not Found
        '500':
          description: Internal error
  '/api/courses/{id}/assignment-groups':
    get:
      tags:
        - api
      summary: Get assignment-groups by ID
      description: |
        Gets assignment-groups by ID
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: query
          description: ID of the course
          required: true
          style: form
          explode: false
          schema: null
          type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  assigments:
                    type: object
                    properties:
                      id:
                        readOnly: true
                        type: string
                      name:
                        type: string
                      courseID:
                        type: int
                      htmlurl:
                        type: string
                      position:
                        type: int
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '404':
          description: Not Found
        '500':
          description: Internal error
