 get:
  tags:
  - Admin
  summary: Get nudges config
  description: |
    Get nudges
  security:
    - bearerAuth: []
  responses:
      200:
        description: Successful operation
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: "../../schemas/nudges/nudges-config.yaml"
      400:
        description: Bad request
      401:
        description: Unauthorized
      500:
        description: Internal error