get:
  tags:
  - Admin
  summary: Get nudges config
  description: |
    Get nudges
  security:
    - bearerAuth: []
  responses:
    200:
      description: Successful operation
      content:
        application/json:
          schema:
            $ref: "../../schemas/nudges/NudgesConfig.yaml"
    400:
      description: Bad request
    401:
      description: Unauthorized
    500:
      description: Internal error
  x-core-function: GetNudgesConfig
  x-data-type: model.NudgesConfig
  x-authentication-type: Permissions
put:
  tags:
    - Admin
  summary: Update the nudges config
  description: |
    Update the nudges config
  security:
    - bearerAuth: []
  requestBody:
    description: update the nudges config
    content:
      application/json:
        schema:
          $ref: "../../../docs/schemas/nudges/NudgesConfig.yaml"
    required: true
  responses:
    200:
      description: Success
      content:
        text/plain:
          schema:
            type: string
            example: Success
    400:
      description: Bad request
    401:
      description: Unauthorized
    500:
      description: Internal error
  x-core-function: UpdateNudgesConfig
  x-data-type: model.NudgesConfig
  x-authentication-type: Permissions
  x-request-body: Def.NudgesConfig
  x-conversion-function: nudgesConfigFromDef