openapi: 3.0.3
info:
  title: Rokwire LMS Building Block API
  description: LMS Building Block API Documentation
  version: 1.9.2
servers:
  - url: 'https://api.rokwire.illinois.edu/lms'
    description: Production server
  - url: 'https://api-test.rokwire.illinois.edu/lms'
    description: Test server
  - url: 'https://api-dev.rokwire.illinois.edu/lms'
    description: Development server
  - url: 'http://localhost/lms'
    description: Local server
tags:
  - name: Api
    description: Clients  APIs.
  - name: Admin
    description: Clients administration APIs.
paths:
  #default
  /version:
    $ref: "./resources/default/version.yaml"

  #api
  /api/courses:
    $ref: "./resources/api/courses/courses.yaml"
  /api/courses/{id}:
    $ref: "./resources/api/courses/coursesID.yaml"
  /api/courses/{id}/assignment-groups:
    $ref: "./resources/api/courses/assigment-groups.yaml"
  /api/courses/{id}/users:
    $ref: "./resources/api/courses/userID.yaml"
  /api/users/self:
    $ref: "./resources/api/user/self.yaml"
  /api/users/courses:
    $ref: "./resources/api/user/courses.yaml"
  /api/users/courses/{id}:
    $ref: "./resources/api/user/coursesID.yaml"
  /api/users/courses/{course-id}/unit/{unit-id}:
    $ref: "./resources/api/user/courses/unitID.yaml"

  #admin
  /admin/nudges-config:
    $ref: "./resources/admin/nudges-config.yaml"
  /admin/nudges:
    $ref: "./resources/admin/nudges/nudges.yaml"
  /admin/nudges/{id}:
    $ref: "./resources/admin/nudges/nudgesID.yaml"
  /admin/sent-nudges:
    $ref: "./resources/admin/sent-nudges.yaml"
  /admin/test-sent-nudges:
    $ref: "./resources/admin/test-sent-nudges.yaml"
  /admin/nudges-processes:
    $ref: "./resources/admin/nudges-process.yaml"
  /admin/courses:
    $ref: "./resources/admin/custom/courses.yaml"
  /admin/courses/{id}:
    $ref: "./resources/admin/custom/coursesID.yaml"
  /admin/modules:
    $ref: "./resources/admin/custom/modules.yaml"
  /admin/modules/{id}:
    $ref: "./resources/admin/custom/modulesID.yaml"
  /admin/units:
    $ref: "./resources/admin/custom/units.yaml"
  /admin/units/{id}:
    $ref: "./resources/admin/custom/unitsID.yaml"
  /admin/content:
    $ref: "./resources/admin/custom/content.yaml"
  /admin/content/{id}:
    $ref: "./resources/admin/custom/contentID.yaml"

components:
  securitySchemes:
      bearerAuth:            # arbitrary name for the security scheme
        type: http
        scheme: bearer
        bearerFormat: JWT
  schemas:
    $ref: "./schemas/index.yaml"
